{
 "title": "Gigamon General",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values with key = hostname"
   },
   {
    "name": "interface",
    "query": "show tag values with key = ifName"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_hostname memtotal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gigamon_stats",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gigamon_stats",
     "select": [
      [
       { "params": [ "sw_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Chassis",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_model",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "model::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gigamon_stats",
     "query": "SELECT mean(\"uptime\") FROM \"gigamon_stats\" WHERE (\"hostname\"::tag =~ /^$host$/ AND \"model\"::tag != '') AND $timeFilter GROUP BY time($__interval), \"model\"::tag fill(none)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "model::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Serial",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_serialnum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "serialnum::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gigamon_stats",
     "query": "SELECT mean(\"uptime\") FROM \"gigamon_stats\" WHERE (\"hostname\"::tag =~ /^$host$/ AND \"serialnum\"::tag != '') AND $timeFilter GROUP BY time($__interval), \"serialnum\"::tag fill(none)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "serialnum::tag", "operator": "!=", "value": "D0343" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "load-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gigamon_stats",
     "select": [
      [
       { "params": [ "load-1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "load-5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gigamon_stats",
     "select": [
      [
       { "params": [ "load-5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "load-15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gigamon_stats",
     "select": [
      [
       { "params": [ "load-15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "memtotal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gigamon_stats",
     "select": [
      [
       { "params": [ "memTotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "memused",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gigamon_stats",
     "query": "SELECT mean(\"memTotal\") - mean(\"memFree\") FROM \"gigamon_stats\" WHERE (\"hostname\"::tag =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"hostname\"::tag fill(none)",
     "select": [
      [
       { "params": [ "memFree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk space used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_hrStorageDescr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hrStorageDescr::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gigamon_storage_table",
     "query": "SELECT mean(\"hrStorageUsed\") / mean(\"hrStorageSize\") *100  FROM \"gigamon_storage_table\" WHERE (\"hostname\"::tag =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"hrStorageDescr\"::tag fill(none)",
     "select": [
      [
       { "params": [ "hrStorageSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " /" ], "type": "math" }
      ],
      [
       { "params": [ "hrStorageUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Fans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "alias": "$tag_fan_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fan_id::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gigamon_env_fans",
     "select": [
      [
       { "params": [ "fan_rpm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gigamon_env_temp",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "PSU",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_psu_id $tag_psu_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "psu_id::tag" ], "type": "tag" },
      { "params": [ "psu_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gigamon_env_psu",
     "select": [
      [
       { "params": [ "psu_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic \"$interface\"",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
     "repeat": "interface",
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gigamon_if_table",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gigamon_if_table",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*-8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Interface *cast/discard/err/queuelen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packet \"$interface\"",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
     "repeat": "interface",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "ucast in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gigamon_if_table",
       "select": [
        [
         { "params": [ "ifHCInUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "ucast out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gigamon_if_table",
       "select": [
        [
         { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "mcast in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gigamon_if_table",
       "select": [
        [
         { "params": [ "ifHCInMulticastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "mcast out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gigamon_if_table",
       "select": [
        [
         { "params": [ "ifHCOutMulticastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "bcast in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gigamon_if_table",
       "select": [
        [
         { "params": [ "ifHCInBroadcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "bcast out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gigamon_if_table",
       "select": [
        [
         { "params": [ "ifHCOutBroadcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "discard in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gigamon_if_table",
       "select": [
        [
         { "params": [ "ifInDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "discard out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gigamon_if_table",
       "select": [
        [
         { "params": [ "ifOutDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "err in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gigamon_if_table",
       "select": [
        [
         { "params": [ "ifInErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "err out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gigamon_if_table",
       "select": [
        [
         { "params": [ "ifOutErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*-1" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "out queue len",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gigamon_if_table",
       "select": [
        [
         { "params": [ "ifOutQLen" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}